In [36]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression

import warnings
warnings.filterwarnings('ignore')
input_data  = pd.read_csv('data/marriage.csv',header=None)

In [21]:
X = input_data.drop([54], axis=1)
y = input_data[54]

In [22]:
X
y

0      1.0
1      1.0
2      1.0
3      1.0
4      1.0
      ... 
165    0.0
166    0.0
167    0.0
168    0.0
169    0.0
Name: 54, Length: 170, dtype: float64

In [24]:
def split(data, target):
    train_data, test_data, train_target, test_target = train_test_split(data, target,test_size=0.2,random_state=1)
    return train_data, test_data, train_target, test_target
train_X, test_X, train_y, test_y = split(X, y)

In [30]:
def KNN(X,y):
    neigh = KNeighborsClassifier(n_neighbors=3)
    return neigh.fit(train_X, train_y)
knn=KNN(train_X,train_y)
knn.predict(test_X)

array([1., 0., 1., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 1., 1., 0., 1., 0., 1., 0., 1., 0., 1., 1., 0., 0., 0.])

In [35]:
def LR(X,y):
    lm = LogisticRegression(random_state=0)
    return lm.fit(X, y)
lr=LR(train_X,train_y)
lr.predict(test_X)

array([1., 0., 1., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 1., 1., 0., 1., 0., 1., 0., 1., 0., 1., 1., 0., 0., 0.])

In [39]:
def NB(X,y):
    gnb = GaussianNB(var_smoothing=1e-3)
    return gnb.fit(X, y)
nb=NB(train_X,train_y)
nb.predict(test_X)

array([1., 0., 1., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 1., 1., 0., 1., 0., 1., 0., 1., 0., 1., 1., 0., 0., 0.])

In [42]:
def pcatrain(data):
    pca_raw = PCA(n_components=2).fit(data) 
    return pca_raw
pca_X=pcatrain(X).transform(X)

array([[ -5.35712022,  -1.77721406],
       [  7.3428233 ,   1.3294768 ],
       [  1.35150733,   3.95561609],
       [  5.43952877,   3.49374067],
       [ -6.13120798,   1.90901645],
       [ -6.56816654,  -0.89070179],
       [  4.36163686,   2.38165012],
       [  3.08816937,   5.23676755],
       [  1.67588729,   6.54768461],
       [ -4.84891119,   0.51216653],
       [ 14.47074326,  -0.12235708],
       [ 16.66229658,   1.01789743],
       [ 12.31194874,   0.87787227],
       [ 12.19026886,   1.15646531],
       [ 12.20624576,   0.64072458],
       [ 13.90857934,   0.27621956],
       [ 14.23928243,   0.91605767],
       [ 14.07543965,   3.69329009],
       [ 14.04519769,   1.06794669],
       [ 12.44619757,   1.49512121],
       [ 13.80700893,  -0.52154061],
       [ 13.94317104,   1.63858127],
       [ 13.35578815,   3.4252923 ],
       [ 11.74612103,  -0.67700591],
       [ 13.31086533,  -1.95021056],
       [ 12.6345737 ,  -1.60126876],
       [ 12.54472794,  -0.50781844],
 

(170, 2)